### ISSUE TITLE
Shows Opp

### ISSUE THREAD

**Issue by jeanhansen** [haasj22/GameInterfaceStratego#4] opened 2019-11-19 16:51 UTC
It shows the opponent's values sometimes which I think is cheating.  I don't think you should be able to see what value their pieces are.

**Comment by haasj22** [comment] 2019-11-19 17:50
We are currently trying to replicate this issue, and once we find the cause of the issue, it will be addressed

**Comment by haasj22** [comment] 2019-11-20 05:27
After spending a good while playtesting, this glitch was unable to be duplicated. We have included various other bug fixes that may have indirectly patched it out, but for now I feel confident closing this bug. That being said, if it future builds, you can duplicate this bug, please leave another issue and we will get to fixing it ASAP.

**Closed as completed by haasj22** 2019-11-20 05:27 UTC
